[[constraint]]
  name = "github.com/nuvo/skbn"
  source = "https://github.com/elastx/skbn.git"
  branch = "master"

[[constraint]]
  name = "github.com/nuvo/cain"
  source = "https://github.com/elastx/cain.git"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true
